name: Java CI with Maven
on:
  schedule:
    - cron: '0,30 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8.0.382+5'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      env:
        OWNER: ${{secrets.OWNER}}
        REPO: ${{secrets.REPO}}
        MY_GITHUB_API_TOKEN: ${{secrets.MY_GITHUB_API_TOKEN}}
      run: mvn -B package --file pom.xml
